// Single source for the public /llms.txt guide.
export const LLMS_TXT =
  [
    "# Wavey Gist",
    "",
    "Wavey Gist publishes Markdown gists at https://gist.wavey.info.",
    "This is the public HTTP guide for agents and scripts.",
    "",
    "## Bases",
    "",
    "- Public frontend: https://gist.wavey.info",
    "- API base: https://api.wavey.info/api/v1",
    "- Publishing API auth: Authorization: Bearer <gist API key>",
    "- Use the current gist id exactly as returned in API field `id`.",
    "",
    "## Public Reading",
    "",
    "These routes do not require authentication:",
    "",
    "- GET https://gist.wavey.info/{gist_id}: rendered gist page.",
    "- GET https://gist.wavey.info/{gist_id}/raw: raw Markdown for the latest revision.",
    "- GET https://gist.wavey.info/{gist_id}/revisions/{revision_number}: rendered revision.",
    "- GET https://gist.wavey.info/{gist_id}/revisions/{revision_number}/raw: raw Markdown for a revision.",
    "- GET https://api.wavey.info/api/v1/gists/{gist_id}/render: JSON rendered payload for the latest revision.",
    "- GET https://api.wavey.info/api/v1/gists/{gist_id}/revisions/{revision_number}/render: JSON rendered payload for a revision.",
    "",
    "Prefer `/raw` when you need Markdown source.",
    "",
    "## Publishing",
    "",
    "Send JSON to https://api.wavey.info/api/v1 with a gist API key.",
    "Use `Content-Type: application/json` and `Authorization: Bearer <gist API key>`.",
    "",
    "Markdown should be complete and self-contained. Prefer starting Markdown with a non-empty `# Title` heading.",
    "Raw Markdown is public to anyone with the gist URL, so do not publish secrets or credentials.",
    "",
    "### Create",
    "",
    "```sh",
    "curl -sS https://api.wavey.info/api/v1/gists \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  --data '{\"title\":\"Example\",\"markdown\":\"# Example\\n\\nMarkdown content.\"}'",
    "```",
    "",
    "### Update",
    "",
    "PATCH accepts `title`, `markdown`, or both. At least one is required.",
    "Omit `title` when the existing title should not change. Omit `markdown` for a title-only revision.",
    "Update only succeeds for gists created by the authenticated key.",
    "",
    "```sh",
    "curl -sS -X PATCH https://api.wavey.info/api/v1/gists/{gist_id} \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  --data '{\"title\":\"Example\",\"markdown\":\"# Example\\n\\nUpdated Markdown content.\"}'",
    "```",
    "",
    "For optimistic concurrency, include `expected_content_sha256` with the current `content_sha256` value.",
    "",
    "### Delete",
    "",
    "```sh",
    "curl -sS -X DELETE https://api.wavey.info/api/v1/gists/{gist_id} \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\"",
    "```",
    "",
    "Delete only succeeds for gists created by the authenticated key.",
    "",
    "## API Responses",
    "",
    "Create and update return JSON including:",
    "",
    "- `id`: current gist id for future API calls.",
    "- `url`: public rendered URL to share.",
    "- `title`: gist title.",
    "- `content_sha256`: SHA-256 digest of the latest Markdown.",
    "- `revision_number` and `latest_revision_number`: current revision metadata.",
    "- `created_at` and `updated_at`: UTC timestamps.",
    "",
    "Use `url` for sharing. Use `id` for update, delete, and API reads.",
    "",
    "## Authenticated Reads And Lists",
    "",
    "- GET https://api.wavey.info/api/v1/gists/{gist_id}: authenticated JSON gist payload including Markdown; requires `gist:read`.",
    "- POST https://api.wavey.info/api/v1/auth/session with JSON `{\"api_key\":\"...\"}`: creates an API web session cookie.",
    "- GET https://api.wavey.info/api/v1/me/gists: JSON list of gists for the API web session.",
    "- GET https://gist.wavey.info/me/raw: plain-text list of gists for the logged-in web session.",
    "- GET https://gist.wavey.info/api/me/gists: JSON list of gists for the logged-in web session.",
    "",
    "Session listing routes require a `wg_session` cookie from login.",
    "To log in through the frontend, POST form field `api_key` to https://gist.wavey.info/api/auth/session.",
    "",
    "## Key Scopes",
    "",
    "- `gist:write`: create gists and update owned gists.",
    "- `gist:read`: authenticated API reads and web sessions.",
    "- `gist:delete`: delete owned gists.",
    "",
    "Public reading by random URL does not require auth.",
    "",
    "## Notes For Agents",
    "",
    "- Do not guess or enumerate gist ids.",
    "- Prefer public `/raw` routes for Markdown source when auth is not needed.",
    "- Preserve the user's Markdown unless they asked you to edit it.",
    "- Never print or publish API keys.",
    "",
  ].join("\n");
