// Single source for the public /llms.txt guide.
export const LLMS_TXT =
  [
    "# Wavey Gist",
    "",
    "Wavey Gist publishes Markdown gists at https://gist.wavey.info.",
    "This is the public HTTP guide for agents and scripts.",
    "",
    "## Bases",
    "",
    "- Public frontend: https://gist.wavey.info",
    "- API base: https://api.wavey.info/api/v1",
    "- Publishing API auth: Authorization: Bearer <gist API key>",
    "- Use the current gist id exactly as returned in API field `id`.",
    "",
    "## Recommended Helper",
    "",
    "Use `publish-gist` for text-only gists. It reads public gists without a key and safely updates owned gists with optimistic concurrency and exact-revision verification.",
    "",
    "Read the latest revision:",
    "",
    "```sh",
    "publish-gist --read --gist <url-or-id> --json",
    "```",
    "",
    "Read a specific revision by passing its revision URL. Without `--json`, read mode prints only Markdown.",
    "",
    "Create from a file:",
    "",
    "```sh",
    "publish-gist --file plan.md --verify --json",
    "```",
    "",
    "Safely update after reading the current digest:",
    "",
    "```sh",
    "publish-gist \\",
    "  --gist <url-or-id> \\",
    "  --file plan.md \\",
    "  --expected-content-sha256 <sha-from-read> \\",
    "  --verify \\",
    "  --json",
    "```",
    "",
    "Writes require `WAVEY_GIST_API_KEY`. `--json` returns the public URL, revision number, and content SHA. `--verify` checks the exact new raw revision, render payload, and public page.",
    "If post-write verification fails, the helper exits nonzero and reports the already-created revision. Inspect that revision; do not blindly publish again.",
    "",
    "## Public Reading",
    "",
    "These routes do not require authentication:",
    "",
    "- GET https://gist.wavey.info/{gist_id}: rendered gist page.",
    "- GET https://gist.wavey.info/{gist_id}/diff: rendered diff from previous revision to latest revision.",
    "- GET https://gist.wavey.info/{gist_id}/raw: raw Markdown for the latest revision.",
    "- GET https://gist.wavey.info/{gist_id}/revisions/{revision_number}: rendered revision.",
    "- GET https://gist.wavey.info/{gist_id}/revisions/{revision_number}/diff: rendered diff from previous revision to this revision.",
    "- GET https://gist.wavey.info/{gist_id}/revisions/{revision_number}/raw: raw Markdown for a revision.",
    "- GET https://api.wavey.info/api/v1/gists/{gist_id}/render: JSON rendered payload for the latest revision.",
    "- GET https://api.wavey.info/api/v1/gists/{gist_id}/revisions/{revision_number}/render: JSON rendered payload for a revision.",
    "",
    "Use these raw HTTP routes when `publish-gist` is unavailable.",
    "",
    "## Publishing",
    "",
    "For images or direct API use, send JSON or multipart forms to https://api.wavey.info/api/v1 with a gist API key.",
    "Use `Authorization: Bearer <gist API key>`.",
    "",
    "Markdown should be complete and self-contained. Prefer starting Markdown with a non-empty `# Title` heading.",
    "Raw Markdown is public to anyone with the gist URL, so do not publish secrets or credentials.",
    "Mermaid diagrams are supported in fenced code blocks tagged `mermaid`; use standard Mermaid syntax and do not rely on renderer-specific extensions.",
    "For Mermaid sequence diagrams, avoid raw semicolons in message text; use a comma, period, or Mermaid entity text such as `#59;` when a literal semicolon is required.",
    "",
    "### Create",
    "",
    "```sh",
    "curl -sS https://api.wavey.info/api/v1/gists \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  --data '{\"title\":\"Example\",\"markdown\":\"# Example\\n\\nMarkdown content.\"}'",
    "```",
    "",
    "### Create With Images",
    "",
    "Use multipart `images[]` fields for new images. Reference an uploaded image as `attachment:<filename>` in Markdown, or omit the reference and it will be appended. `markdown` can be omitted when creating an image-only gist.",
    "",
    "```sh",
    "curl -sS https://api.wavey.info/api/v1/gists \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\" \\",
    "  -F 'title=Example' \\",
    "  -F 'markdown=# Example\\n\\n![Chart](attachment:chart.png)' \\",
    "  -F 'images[]=@chart.png'",
    "```",
    "",
    "### Upload One Image",
    "",
    "```sh",
    "curl -sS https://api.wavey.info/api/v1/images \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\" \\",
    "  -F 'image=@chart.png'",
    "```",
    "",
    "### Update",
    "",
    "PATCH accepts `title`, `markdown`, or both. At least one is required.",
    "Omit `title` when the existing title should not change. Omit `markdown` for a title-only revision.",
    "Update only succeeds for gists created by the authenticated key.",
    "",
    "```sh",
    "curl -sS -X PATCH https://api.wavey.info/api/v1/gists/{gist_id} \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\" \\",
    "  -H \"Content-Type: application/json\" \\",
    "  --data '{\"title\":\"Example\",\"markdown\":\"# Example\\n\\nUpdated Markdown content.\"}'",
    "```",
    "",
    "For optimistic concurrency, include `expected_content_sha256` with the current `content_sha256` value.",
    "For updates with new images, send multipart fields `markdown`, optional `title`, optional `expected_content_sha256`, and repeated `images[]` files.",
    "",
    "### Delete",
    "",
    "```sh",
    "curl -sS -X DELETE https://api.wavey.info/api/v1/gists/{gist_id} \\",
    "  -H \"Authorization: Bearer $WAVEY_GIST_API_KEY\"",
    "```",
    "",
    "Delete only succeeds for gists created by the authenticated key.",
    "",
    "## API Responses",
    "",
    "Create and update return JSON including:",
    "",
    "- `id`: current gist id for future API calls.",
    "- `url`: public rendered URL to share.",
    "- `title`: gist title.",
    "- `content_sha256`: SHA-256 digest of the latest Markdown.",
    "- `revision_number` and `latest_revision_number`: current revision metadata.",
    "- `created_at` and `updated_at`: UTC timestamps.",
    "- Multipart image create/update responses also include final `markdown` and an `images` list.",
    "- Public render responses include the exact revision's `content_sha256` with Markdown and revision metadata.",
    "",
    "Use `url` for sharing. Use `id` for update, delete, and API reads.",
    "",
    "## Authenticated Reads And Lists",
    "",
    "- GET https://api.wavey.info/api/v1/gists/{gist_id}: authenticated JSON gist payload including Markdown.",
    "- POST https://api.wavey.info/api/v1/auth/session with JSON `{\"api_key\":\"...\"}`: creates an API web session cookie.",
    "- GET https://api.wavey.info/api/v1/me/gists: JSON list of gists for the API web session.",
    "- GET https://gist.wavey.info/me/raw: plain-text list of gists for the logged-in web session.",
    "- GET https://gist.wavey.info/api/me/gists: JSON list of gists for the logged-in web session.",
    "",
    "Session listing routes require a `wg_session` cookie from login.",
    "To log in through the frontend, POST form field `api_key` to https://gist.wavey.info/api/auth/session.",
    "",
    "## Key Permissions",
    "",
    "A gist API key can create gists and update/delete gists created by that key.",
    "Public reading by random URL does not require auth.",
    "",
    "## Notes For Agents",
    "",
    "- Do not guess or enumerate gist ids.",
    "- Gist ids are base62 strings containing 16–64 ASCII letters or digits.",
    "- API requests reject unknown fields. Gist multipart uploads use repeated `images[]`; standalone image upload uses one `image`.",
    "- Preserve the user's Markdown unless they asked you to edit it.",
    "- Never print or publish API keys.",
    "",
  ].join("\n");
